# Generated by Django 4.1.5 on 2023-01-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_remove_authorimage_authors_remove_book_authors_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='books',
            field=models.ManyToManyField(blank=True, to='book.book'),
        ),
    ]
