# Generated by Django 4.1.5 on 2023-01-22 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='books',
        ),
    ]
