# Generated by Django 4.1.5 on 2023-01-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='books', to='book.book'),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ManyToManyField(related_name='images', to='book.bookimage'),
        ),
    ]
