# Generated by Django 4.1.5 on 2023-01-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_author_books_book_description_book_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_image', models.ImageField(upload_to='book')),
            ],
        ),
        migrations.RenameField(
            model_name='book',
            old_name='image',
            new_name='images',
        ),
        migrations.AddField(
            model_name='author',
            name='images',
            field=models.ManyToManyField(related_name='images', to='book.authorimage'),
        ),
    ]
