# Generated by Django 4.1.5 on 2023-01-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_authorimage_rename_image_book_images_author_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='images',
            field=models.ManyToManyField(related_name='author_images', to='book.authorimage'),
        ),
        migrations.AlterField(
            model_name='book',
            name='images',
            field=models.ManyToManyField(related_name='book_images', to='book.bookimage'),
        ),
    ]
