# Generated by Django 4.1.5 on 2023-01-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_author_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorimage',
            name='file_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bookimage',
            name='file_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='books', to='book.book'),
        ),
        migrations.AlterField(
            model_name='authorimage',
            name='author_image',
            field=models.ImageField(upload_to='authors'),
        ),
    ]
