# Generated by Django 4.1.5 on 2023-01-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_authorimage_file_name_bookimage_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(null=True, related_name='books', to='book.book'),
        ),
        migrations.AlterField(
            model_name='author',
            name='images',
            field=models.ManyToManyField(null=True, related_name='author_images', to='book.authorimage'),
        ),
        migrations.AlterField(
            model_name='book',
            name='images',
            field=models.ManyToManyField(null=True, related_name='book_images', to='book.bookimage'),
        ),
    ]
