# Generated by Django 4.1.5 on 2023-01-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_author_books_alter_author_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='author_images', to='book.authorimage'),
        ),
        migrations.AlterField(
            model_name='book',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='book_images', to='book.bookimage'),
        ),
    ]
