# Generated by Django 4.1.5 on 2023-01-14 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_author_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorimage',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.author'),
        ),
        migrations.AddField(
            model_name='bookimage',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
    ]
