# Generated by Django 4.1.5 on 2023-01-14 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorimage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bookimage',
            name='book',
        ),
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
        migrations.RemoveField(
            model_name='author',
            name='images',
        ),
        migrations.RemoveField(
            model_name='book',
            name='images',
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.book'),
        ),
        migrations.AddField(
            model_name='author',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_images', to='book.authorimage'),
        ),
        migrations.AddField(
            model_name='book',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_images', to='book.bookimage'),
        ),
    ]
