# Generated by Django 4.1.5 on 2023-01-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_remove_authorimage_author_remove_book_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
        migrations.RemoveField(
            model_name='author',
            name='images',
        ),
        migrations.RemoveField(
            model_name='book',
            name='images',
        ),
        migrations.AddField(
            model_name='authorimage',
            name='authors',
            field=models.ManyToManyField(null=True, related_name='author_image', to='book.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(null=True, related_name='book_author', to='book.author'),
        ),
        migrations.AddField(
            model_name='bookimage',
            name='books',
            field=models.ManyToManyField(null=True, related_name='book_images', to='book.book'),
        ),
    ]
