# Generated by Django 4.1.5 on 2023-01-26 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0016_remove_bookimage_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookimage',
            name='file_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bookimage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
