# Generated by Django 4.1.5 on 2023-01-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_order_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='order_books', to='book.book'),
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
